In [34]:
import numpy as np

1. Create a numpy array from list

In [35]:
arr = [1, 2, 3, 4]
nparr = np.array(arr)
print(type(nparr), nparr)

<class 'numpy.ndarray'> [1 2 3 4]


2. Access elements of a numpy array

In [36]:
a, b = nparr[0], nparr[1]
print(f"a: {a}, b: {b}")

a: 1, b: 2


3. Use numpy arrays to perform vector operations

In [37]:
a = np.array([1, 2, 3, 4])
b = np.array([2, 3, 4, 5])

# perform vector addititon
vec_add = a + b
vec_sub = a - b
vec_dot = a * b

print(f"Addition: {vec_add}")
print(f"Subtraction: {vec_sub}")
print(f"Dot Product: {vec_dot}")

Addition: [3 5 7 9]
Subtraction: [-1 -1 -1 -1]
Dot Product: [ 2  6 12 20]


4. Create numpy array of any shape filled with zeros

In [38]:
# the shape of the array is (2, 3, 4)
zero_arr = np.zeros((2, 3, 4))
print(zero_arr)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


5. Create numpy array of any shape filled with ones

In [39]:
ones_arr = np.ones((2, 3, 4))
print(ones_arr)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


6. Create numpy array of any shape filled with any arbitrary number

In [40]:
# create a np array filled with number 9
num_arr = np.full((2, 3, 4), 9)
print(num_arr)

[[[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]

 [[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]]


7. Create numpy array with random values

In [41]:
# generates random values between 0 and 1
random_arr = np.random.random((2, 4))
print(random_arr)

[[0.65444428 0.81410375 0.93808472 0.04691661]
 [0.81852942 0.08107404 0.02054264 0.70545705]]


8. Generate values in a given range with equal gap 

In [42]:
# generates 10 values in the range [0, 100)
x = np.arange(0, 100, 10)
print(f"x: {x}")

# use x as an independent variable to a function y
y = x**2 + 3
print(f"Respective values of y for the given x: {y}")

x: [ 0 10 20 30 40 50 60 70 80 90]
Respective values of y for the given x: [   3  103  403  903 1603 2503 3603 4903 6403 8103]


9. Generate a set of evenly distributed values in a given range

In [43]:
x = np.linspace(0, 100, 15)
print(x)

[  0.           7.14285714  14.28571429  21.42857143  28.57142857
  35.71428571  42.85714286  50.          57.14285714  64.28571429
  71.42857143  78.57142857  85.71428571  92.85714286 100.        ]


10. Find the shape of an array

In [44]:
a = np.array([
    [
        [2, 3],
        [4, 5]
    ],
    [
        [6, 7],
        [3, 9]
    ]
])
shape = a.shape
shape

(2, 2, 2)

11. Find the data type of numpy array

In [45]:
# print the data type of a 
print(a.dtype)

int32


12. Create a np array with desired data type

In [48]:
# create an array with float data type
x = np.array([
    [2, 3],
    [3, 4]
], dtype=float)
print(x)

[[2. 3.]
 [3. 4.]]


### Numpy Functions

1. Mathematical Functions

In [57]:
a = np.array([
    [1, 2, 3, 4],
    [6, 7, 8, 9]
])

# trigonometric functions sin/cos/tan
print(f"sin a: {np.sin(a)}")

sin a: [[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
 [-0.2794155   0.6569866   0.98935825  0.41211849]]


In [56]:
# exponential function
print(f"e^a: {np.exp(a)}")

e^a: [[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01]
 [4.03428793e+02 1.09663316e+03 2.98095799e+03 8.10308393e+03]]


In [58]:
# logarithmic function
print(f"log a: {np.log(a)}")

log a: [[0.         0.69314718 1.09861229 1.38629436]
 [1.79175947 1.94591015 2.07944154 2.19722458]]


In [59]:
# square root function
print(f"sqrt a: {np.sqrt(a)}")

sqrt a: [[1.         1.41421356 1.73205081 2.        ]
 [2.44948974 2.64575131 2.82842712 3.        ]]


2. Aggregate Functions

In [64]:
print(f"Sum: {a.sum()} Min: {a.min()} Max: {a.max()}")

# statistical functions
print(f"Mean: {a.mean()} Median: {np.median(a)} Standard Deviation: {np.std(a)}")

Sum: 40 Min: 1 Max: 9
Mean: 5.0 Median: 5.0 Standard Deviation: 2.7386127875258306


3. Shape Manipulation Functions

In [69]:
# reshape the array while maintaining the size
print(f"Size: {a.size} Shape: {a.shape}")
print(a)

Size: 8 Shape: (2, 4)
[[1 2 3 4]
 [6 7 8 9]]


In [75]:
# reshape a to a 3D array with a shape (2, 2, 2)
a = a.reshape((2, 2, 2))
print(f"Size: {a.size} Shape: {a.shape}")
print(a)

Size: 8 Shape: (2, 2, 2)
[[[1 2]
  [3 4]]

 [[6 7]
  [8 9]]]


In [72]:
# flatten the array to one dimension
print(f"Flatten: {a.flatten()}")

Flatten: [1 2 3 4 6 7 8 9]


In [77]:
# get the transpose of an array rows <--> cols
a = np.array([
    [1, 2, 3, 4],
    [6, 7, 8, 9]
])
print(a.transpose())

[[1 6]
 [2 7]
 [3 8]
 [4 9]]


4. Join two arrays

In [82]:
x = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

y = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

# join row-wise without changing the dimensions
c = np.concatenate((x, y))
# stack creates a new dimension
s = np.stack((x, y), axis=1)

print(f"Concatenate: {c} Shape: {c.shape}")
print(f"Stack: {s} Shape: {s.shape}")

Concatenate: [[ 1  2  3]
 [ 4  5  6]
 [10 20 30]
 [40 50 60]] Shape: (4, 3)
Stack: [[[ 1  2  3]
  [10 20 30]]

 [[ 4  5  6]
  [40 50 60]]] Shape: (2, 2, 3)
